# Generated by Django 3.1.7 on 2021-02-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='image',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='datapool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.datapool'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='scientist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.scientist'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.dataentry')),
                ('scientist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.scientist')),
            ],
        ),
    ]
