# Generated by Django 3.1.7 on 2021-02-27 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20210226_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
