# Generated by Django 3.1.7 on 2021-02-27 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20210226_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='date',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
