# Generated by Django 3.1.7 on 2021-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20210226_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
