# Generated by Django 3.1.7 on 2021-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_datapool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapool',
            name='document',
            field=models.FileField(default=0, upload_to='references/'),
            preserve_default=False,
        ),
    ]
