# Generated by Django 3.1.7 on 2021-02-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_datapool_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapool',
            name='category',
            field=models.CharField(choices=[('Ecology', 'ECOLOGY'), ('Sociology', 'SOCIOLOGY'), ('Astronomy', 'ASTRONOMY'), ('Geology', 'GEOLOGY')], default='Ecology', max_length=25),
        ),
    ]
