# Generated by Django 3.1.7 on 2021-02-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_datapool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.scientist'),
        ),
    ]
