# Generated by Django 3.1.7 on 2021-02-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20210227_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapool',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
