# Generated by Django 3.1.7 on 2021-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_datapool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='github',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='twitter',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='website',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
