# Generated by Django 3.1.7 on 2021-02-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20210227_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientist',
            name='github',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='website',
        ),
    ]
