# Generated by Django 3.1.7 on 2021-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20210227_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
