# Generated by Django 3.1.7 on 2021-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_scientist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='datapool',
            name='document',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='answers',
            field=models.TextField(blank=True, default='Answer the questions here!', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='datapool',
            name='questions',
            field=models.TextField(blank=True, default='Ask your questions here!', max_length=300, null=True),
        ),
    ]
