# Generated by Django 3.1.7 on 2021-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_auto_20210228_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='entry_cap',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
