# Generated by Django 3.1.7 on 2021-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_dataentry_entry_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='entry_cap',
        ),
        migrations.AddField(
            model_name='datapool',
            name='entry_cap',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
