# Generated by Django 3.1.7 on 2021-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_auto_20210228_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
